source "https://rubygems.org"

gem "rails", "4.2.1"

gem "acts-as-taggable-on"
gem "awesome_nested_set"
gem "aws-sdk", "< 2.0" # paperclip compatibility
gem "bootstrap-growl-rails"
gem "cancancan"
gem "carmen-rails"
gem "coffee-rails"
gem "config_spartan"
gem "devise"
gem "devise-i18n"
gem "envyable"
gem "ey_config"
gem "font-awesome-rails"
gem "friendly_id"
gem "friendly_id-globalize", "~> 1.0.0.alpha1"
gem "globalize"
gem "haml"
gem "jquery-fileupload-rails"
gem "jquery-infinite-pages"
gem "jquery-rails", "3.1.2"
gem "jquery_mobile_rails", "1.4.5"
gem "kaminari"
gem "mobylette"
gem "modernizr-rails"
gem "mysql2"
gem "paperclip"
gem "paperclip-meta"
gem "protected_attributes"
gem "rails-i18n"
gem "ransack"
gem "sanitize"
gem "sass-rails"
gem "sentry-raven"
gem "simple_form"
gem "sqlite3"
gem "tinymce-rails"
gem "tinymce-rails-langs"
gem "uglifier"

group :development do
  gem "pry"
  gem "thin"
end
